services:
  database:
    image: golang:1.22-alpine3.19
    command:
      go run /mock-db/main.go
    ports:
      - "1212:1212"
    volumes:
      - ./mock-db/:/mock-db

  database-migrations:
    image: alpine:3.19
    command:
      wget --no-verbose --tries=1 --spider http://database:1212/db
    depends_on:
      - database
    restart: on-failure

  public-api:
    image: golang:1.22-alpine3.19
    command:
      go run /api/main.go
    volumes:
      - ./api/:/api
    ports:
      - "8080:8080"
    depends_on:
      database-migrations:
        condition: service_completed_successfully
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  web-service:
    image: golang:1.22-alpine3.19
    command:
      go run /web/main.go
    volumes:
      - ./web-service/:/web
    ports:
      - "8081:8080"
    depends_on:
      public-api:
        condition: service_healthy
